<style>
    /* Bordered form */
    form {
        border: 3px solid #f1f1f1;
    }

    /* Full-width inputs */
    input[type=text], input[type=password] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        box-sizing: border-box;
    }

    /* Set a style for all buttons */
    .popup-btn {
        color:#1a1a1a;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: auto;
        display: block;
        position: relative;
        left: 46%;
    }

    /* Add a hover effect for buttons */
    button:hover {
        opacity: 0.8;

    }

    /* Add padding to containers */
    .container {
        padding: 16px;
        position: relative;
    }

    /* The "Forgot password" text */
    span.psw {
        display: block;
        padding-top: 16px;
        text-align: center;
    }

    /* Change styles for span and cancel button on extra small screens */
    @media screen and (max-width: 300px) {
        span.psw {
            display: block;
            float: none;
        }
    }
    .modal-footer{
        display: none;
    }
</style>

<div id="element" >
    <button class="btn" onclick="sayHello()">Open Modal</button>
    <button class="btn2">Open Magento Login Modal </button>
    <button class="btn3">Open Custom Login Modal</button>
</div>

<form class="popup-modal">
    <h3>Login Modal</h3>
    <div class="container">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" required>

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required>

        <button class="popup-btn" type="submit">Login</button>

        <span class="psw">Not Registered? <a href="#"> Create an account.</a></span>
    </div>
</form>

<script>
    function sayHello() {
        window.alert('Hello World');
    }
    // require([
    //         'jquery',
    //         'Magento_Ui/js/modal/modal'
    //     ],
    //     function($, modal) {
    //         var options = {
    //             type: 'popup',
    //             responsive: true,
    //             innerScroll: true,
    //         };
    //
    //         var popup = modal(options, $('.popup-modal'));
    //         $(".btn2").on('click',function(){
    //             $(".popup-modal").modal("openModal");
    //         });
    //     });
    //
    // require([
    //     'jquery',
    //     'Magento_Ui/js/modal/alert'
    // ], function ($,alert) {
    //         $(".btn").on('click',function(){
    //             alert({
    //                 title: "HelloWorld Modal"
    //                 content: "HelloWorld"
    //                 action: {
    //                     always: function(){}
    //                 }
    //             });
    //         })
    //     });
</script>