<?php
namespace Magenest\Movie\Model\ResourceModel\Movie;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection {
    public function _construct() {
        $this->_init('Magenest\Movie\Model\Movie', 'Magenest\Movie\Model\ResourceModel\Movie');
    }

    protected function _initSelect()
    {
        parent::_initSelect (); // TODO: Change the autogenerated stub

        $condition = 'main_table.director_id = magenest_director.director_id';


        $this->getSelect()->join(
            ['magenest_director' => $this->getTable('magenest_director')], //2nd table name by which you want to join mail table
            'main_table.director_id = magenest_director.director_id', // common column which available in both table
            ['director_name' => 'magenest_director.name']// '*' define that you want all column of 2nd table. if you want some particular column then you can define as ['column1','column2']
        );
    }
}