<h3>Movie</h3>
<table style="width:100%" border="1">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Description</th>
        <th>Rating</th>
        <th>Director</th>
        <th>Actor</th>
    </tr>
    <?php foreach ($block->getMovie() as $item):?>
        <tr>
            <td><?php echo $item->getData('movie_id') ?></td>
            <td><?php echo $item->getData('name') ?></td>
            <td><?php echo $item->getData('description') ?></td>
            <td><?php echo $item->getData('rating') ?></td>
            <td>
                <?php echo  $item->getData ('director_name')?>
<!--                --><?php //foreach ($block->getDirector() as $dir):?>
<!--                    --><?php //if ($item->getData('director_id') == $dir->getData ('director_id')){?>
<!--                        --><?php //echo $dir->getData ('name'); }?>
<!--                --><?php //endforeach; ?>
            </td>
            <td>
                <?php foreach ($block->getMovieActor() as $movieActor):?>
                    <?php if ($item->getData('movie_id') == $movieActor->getData ('movie_id')){?>
                        <?php foreach ($block->getActor() as $actor):?>
                            <?php if ($movieActor->getData('actor_id') == $actor->getData ('actor_id')){?>
                                <p> <?php echo $actor->getData ('name'); ?> </p>
                                <?php } ?>
                        <?php endforeach; }?>
                <?php endforeach; ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<h3>Director</h3>
<table style="width:100%" border="1">
    <tr>
        <th>Id</th>
        <th>Name</th>
    </tr>
    <?php foreach ($block->getDirector() as $item):?>
        <tr>
            <td><?php echo $item->getData('director_id') ?></td>
            <td><?php echo $item->getData('name') ?></td>
        </tr>
    <?php endforeach; ?>
</table>
<h3>Actor</h3>
<table style="width:100%" border="1">
    <tr>
        <th >Id</th>
        <th >Name</th>
    </tr>
    <?php foreach ($block->getActor() as $item):?>
        <tr>
            <td><?php echo $item->getData('actor_id') ?></td>
            <td><?php echo $item->getData('name') ?></td>
        </tr>
    <?php endforeach; ?>
</table>