
<?php foreach ($block->getCustomerCollection($block->getSessionID()) as $item):?>
    <p>
        <?php echo $item->getData('firstname') ?>
        <?php echo $item->getData('lastname') ?>
    </p>
    <p>
        <?php echo $item->getData('email') ?>
    </p>
    <p>
        <?php echo $item->getData('avata_image') ?>
    </p>
    <img src="<?php echo
        "http://localhost/m-228/admin/customer/index/viewfile/image/"
        .base64_encode ($item->getData ('avata_image'))?>" height="300" width="200">
<?php endforeach; ?>
